# Generated by Django 5.1.1 on 2024-09-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0003_baner_remove_category_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baner',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
