# Generated by Django 5.1.1 on 2024-09-28 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0005_remove_category_description_cat_popular_topics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Baner',
            new_name='Banner',
        ),
        migrations.AlterField(
            model_name='cart',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='udemy.student'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='udemy.category'),
        ),
        migrations.CreateModel(
            name='PopularTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_topics', to='udemy.cat')),
            ],
        ),
        migrations.DeleteModel(
            name='popular_topics',
        ),
    ]
