# Generated by Django 5.1.1 on 2024-09-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0006_rename_baner_banner_alter_cart_student_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cat',
            new_name='Cupcategory',
        ),
        migrations.RenameField(
            model_name='populartopic',
            old_name='cat',
            new_name='Cupcategory',
        ),
    ]
